### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by crackofdusk** [rails/pjax_rails#84]
Since the 0.4.0 release, pjax_rails has updated to pjax 1.9.6 and gained support for rails 5. I think it makes sense to release a new version.

However a new release is blocked by the following:
- [ ] Decide which versions of rails to support. (The current [Rails maintenance policy](http://guides.rubyonrails.org/maintenance_policy.html) excludes versions before 4.2. Do we also remove support for them? Do we maintain backward compatibility?)
- [ ] Fix the build accordingly. (The build is currently broken for various combinations of ruby implementation, ruby version and rails version.)

I am willing to help with fixing the build.

Feel free to add items I have forgotten.

**Comment by colleenbprice** [comment]
It would be really great if you could get 0.5.0 out soon because it contains the fix for the user agent string, which was disabling pjax in IOS 10. We have had to manually fix it on our site for now.

**Comment by stevelacey** [comment]
Yes, I also want the `Only blur the focus if the focused element is within the container` fix that is in newer pjax

**Comment by markets** [comment]
Hi everybody :wave: 

Long time since latest release and current master have a lot of interesting fixes: https://github.com/rails/pjax_rails/compare/v0.4.0...master#files_bucket and even Rails 5 and 6 (merged today #88) support. Do you think we can push a new release to RubyGems? 

About the original blockers defined in the OP:

- Rails compatibility: while it works, we can keep current matrix, why not?
- Fix CI: current CI is passing, so we can consider this point :white_check_mark: 

Let me know if I can do something to help moving this forward!

**Comment by route** [comment]
@markets sounds good to me, I will prepare release today. Thanks!

**Comment by route** [comment]
Just released

**Comment by route** [comment]
@markets thanks almost forgot about that ;)
